# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LOGIN_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Login_App

  target 'LOGIN_AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LOGIN_AppUITests' do
    # Pods for testing
  end

    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
    pod 'FirebaseFirestoreSwift'
    pod "GMStepper"




end
